# Load libraries
library(shiny)
library(shinydashboard)
library(shinycssloaders)
library(palmerpenguins)
library(tidyverse)
library(dplyr)
library(leaflet)
library(leaflet.extras)
library(leaflet.minicharts)
